### ISSUE TITLE
EPIC: Implement QGB integration tests

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/orchestrator-relayer#116]
We will need to test the QGB behavior in a bigger network and have integration tests for that. 

We could be inspired from QGB V1 [E2E](https://github.com/celestiaorg/celestia-app/tree/qgb-integration/e2e/qgb) and extend them to support the P2P network and run similar testing scenarios.

- [x] https://github.com/celestiaorg/orchestrator-relayer/issues/163
- [x] https://github.com/celestiaorg/orchestrator-relayer/issues/164
- [x] https://github.com/celestiaorg/orchestrator-relayer/issues/165
- [x] https://github.com/celestiaorg/orchestrator-relayer/issues/166
- [x] https://github.com/celestiaorg/orchestrator-relayer/issues/167
- [x] https://github.com/celestiaorg/orchestrator-relayer/issues/168
- [x] https://github.com/celestiaorg/orchestrator-relayer/issues/162
- [x] https://github.com/celestiaorg/orchestrator-relayer/issues/169
- [x] https://github.com/celestiaorg/orchestrator-relayer/issues/183
