### ISSUE TITLE
EPIC Copy the existing code from the app repo

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/orchestrator-relayer#15]
Multiple parts of the orchestrator and relayer were already implemented in the Celestia-app repo, under the `qgb-integration` branch.
We will need to copy those parts to this repository, not to re-implement everything.

The parts to be copied are mainly:

- [x] https://github.com/celestiaorg/orchestrator-relayer/issues/12
- [x] https://github.com/celestiaorg/orchestrator-relayer/issues/11
- [x] https://github.com/celestiaorg/orchestrator-relayer/issues/13
- [x] https://github.com/celestiaorg/orchestrator-relayer/issues/14
- [x] https://github.com/celestiaorg/orchestrator-relayer/issues/19
