### ISSUE TITLE
QGB v2 Beta tracker

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/orchestrator-relayer#203]
After finishing the QGB v2 MVP https://github.com/celestiaorg/orchestrator-relayer/issues/92, we should think of having a beta version that can be run also by some validators to get their feedback.

This version should focus more on how the users interact with the QGB binary, and also add more stability to it. 

This issue will serve as a tracker for it:

## High priority

- [ ] https://github.com/celestiaorg/orchestrator-relayer/issues/200
- [ ] https://github.com/celestiaorg/orchestrator-relayer/issues/181
- [ ] https://github.com/celestiaorg/orchestrator-relayer/issues/148
- [ ] https://github.com/celestiaorg/orchestrator-relayer/issues/147
- [ ] https://github.com/celestiaorg/orchestrator-relayer/issues/91
- [ ] https://github.com/celestiaorg/orchestrator-relayer/issues/75
- [ ] https://github.com/celestiaorg/orchestrator-relayer/issues/64
- [ ] https://github.com/celestiaorg/orchestrator-relayer/issues/22

## Low priority

- [ ] https://github.com/celestiaorg/orchestrator-relayer/issues/152
- [ ] https://github.com/celestiaorg/orchestrator-relayer/issues/146
- [ ] https://github.com/celestiaorg/orchestrator-relayer/issues/145
- [ ] https://github.com/celestiaorg/orchestrator-relayer/issues/139
- [ ] https://github.com/celestiaorg/orchestrator-relayer/issues/16

## Stretch

- [ ] https://github.com/celestiaorg/orchestrator-relayer/issues/176
- [ ] https://github.com/celestiaorg/orchestrator-relayer/issues/1
