### ISSUE TITLE
EPIC: Implement commands

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/orchestrator-relayer#46]
After that the backbone of the commands has been added by https://github.com/celestiaorg/orchestrator-relayer/pull/40. We should complete their implementation:

- [x] https://github.com/celestiaorg/orchestrator-relayer/issues/47
- [x] https://github.com/celestiaorg/orchestrator-relayer/issues/48
- [x] https://github.com/celestiaorg/orchestrator-relayer/issues/49
