### ISSUE TITLE
Implement validators for the DHT values

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/orchestrator-relayer#74]
As specified in the P2P ADR https://github.com/celestiaorg/orchestrator-relayer/pull/66, we will use record validators to validate the values posted on the DHT. These values will be either `DataCommitmentConfirm`s or `ValsetConfirm`s. Thus, we could run stateless checks on them to add an extra layer of security when posting/querying for confirms.

- [x] https://github.com/celestiaorg/orchestrator-relayer/issues/72
- [x] https://github.com/celestiaorg/orchestrator-relayer/issues/73
- [x] https://github.com/celestiaorg/orchestrator-relayer/issues/225
- [x] https://github.com/celestiaorg/orchestrator-relayer/issues/224
