### ISSUE TITLE
QGB V2 MVP tracker

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/orchestrator-relayer#92]
This issue will act as a QGB V2 MVP tracker:

### High priority

- [ ] https://github.com/celestiaorg/orchestrator-relayer/issues/42
- [ ] https://github.com/celestiaorg/orchestrator-relayer/issues/55
- [ ] https://github.com/celestiaorg/orchestrator-relayer/issues/78

### Low priority

- [ ] https://github.com/celestiaorg/orchestrator-relayer/issues/66

### Stretch

- [ ] https://github.com/celestiaorg/orchestrator-relayer/issues/91
